name: ESP32 Filesystem Build

on:
  push:
    branches:
      - main
      - feat/actions-build
  pull_request:
    branches:
      - main

jobs:
  build_filesystem:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t esp32-builder -f Dockerfile .

    - name: Run container and generate fs.bin
      run: |
        docker run --name esp32-fs-builder esp32-builder /bin/bash
        docker cp esp32-fs-builder:/fs.bin .

    - name: Prepara Firmware Oficial e Configuracoes Wokwi
      run: |
        # 1. Baixa uma versao estavel garantida do MicroPython (v1.19.1) via curl
        curl -L -f -o micropython_oficial.bin https://micropython.org/resources/firmware/esp32-20220618-v1.19.1.bin
        
        # 2. Cria um flasher_args limpo unindo o OS oficial com o seu sistema de arquivos Docker
        cat << 'EOF' > flasher_args.json
        {
          "flash_files": {
            "0x1000": "micropython_oficial.bin",
            "0x200000": "fs.bin"
          },
          "extra_esptool_args": {
            "after": "hard_reset",
            "before": "default_reset",
            "stub": true,
            "chip": "esp32"
          }
        }
        EOF
        
        # 3. Recria o wokwi.toml para satisfazer a exigencia da CLI
        cat << 'EOF' > wokwi.toml
        [wokwi]
        version = 1
        firmware = "flasher_args.json"
        EOF

    - name: Test with Wokwi
      uses: wokwi/wokwi-ci-action@v1
      with:
        token: ${{ secrets.WOKWI_CLI_TOKEN }}
        path: .
        timeout: 60000
        expect_text: 'Teste'